services:
  circulations:
      build: .
      command: >
              bash -c "python manage.py makemigrations &&
                          python manage.py migrate &&
                          python manage.py load_data &&
                          python manage.py runserver 0.0.0.0:8000"
      volumes:
          - .:/usr/src/app/
      ports:
          - "8000:8000"
      environment:
          - DEBUG=1
          - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
          - CELERY_BROKER=redis://redis:6379/0
          - CELERY_BACKEND=redis://redis:6379/0
      depends_on:
          - postgres
          - redis
  celery:
      build: .
      command: celery -A celery_app worker -l INFO
      volumes:
          - .:/usr/src/app
      environment:
          - DEBUG=1
          - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
          - CELERY_BROKER=redis://redis:6379/0
          - CELERY_BACKEND=redis://redis:6379/0
      depends_on:
          - circulations
          - redis
  postgres:
      image: postgres
      environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
      volumes:
          - pgdata:/var/lib/postgresql/data/
  redis:
      image: "redis:alpine"
      
volumes:
  pgdata:
